### ISSUE TITLE
Problem with Python 3.5

### ISSUE THREAD

**Issue by haje01** [cybertronai/pytorch-lamb#1]
I'm using Amazon SageMaker & PyTorch.
I have following error with SageMaker's PyTorch Estimator:

```
Traceback (most recent call last):
File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/opt/ml/code/lstmauto.py", line 15, in <module>
from pytorch_lamb import Lamb
File "/usr/local/lib/python3.5/dist-packages/pytorch_lamb/__init__.py", line 1, in <module>
from .lamb import Lamb, log_lamb_rs
File "/usr/local/lib/python3.5/dist-packages/pytorch_lamb/lamb.py", line 21
event_writer.add_histogram(f'lamb/{k}', torch.tensor(v), token_count)
```

In my opinion, it is caused by f-string syntax which requires Python 3.6 or above, but SageMaker's PyTorch Estimator only supports Python 3.5

It would be great if I could use Lamb in Python 3.5
Thank you.

**Comment by yaroslavvb** [comment]
All of Amazon's DLAMI images support Python 3.6, I wonder what's the deal with SageMaker being stuck on 3.5
f-string are so nice....
